version: '3.8'

services:

  web:
    build: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - geo-distance

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_route_api
    ports:
      - "5432:5432"
    networks:
      - geo-distance

networks:
  geo-distance:
    driver: bridge